# Generated by Django 3.1 on 2020-10-09 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.CharField(max_length=120)),
                ('age', models.CharField(max_length=120)),
                ('email', models.CharField(max_length=120, unique=True)),
                ('mobile', models.CharField(max_length=120, unique=True)),
                ('productid', models.IntegerField()),
            ],
        ),
    ]
