# Generated by Django 3.1 on 2020-10-09 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_orders_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='email',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='orders',
            name='mobile',
            field=models.CharField(max_length=120),
        ),
    ]
