# Generated by Django 3.1 on 2020-10-12 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20201010_0509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='productid',
        ),
        migrations.AddField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('ordered', 'ordered'), ('cancelled', 'cancelled')], default='ordered', max_length=20),
        ),
    ]
